apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "FCG.UsersAPI"
  Jwt__Audience: "FCG.Platform"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__Username: "guest"
